spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.zhu.aqs.typehandler
mapper:
  mappers:
  - com.zhu.aqs.lib.MyBaseMapper
  not-empty: false
  identity: mysql
